### ISSUE TITLE
The PCD contains placeholders

### ISSUE THREAD

**Issue by palemieux** [SMPTE/rp2129#1]
The document contains placeholder such as "If this is a revision, a topical list of changes [should/shall] be included here."

**Comment by danielsmpte** [comment]
New to GitHub so I'll need to figure out what your just told me

**Comment by palemieux** [comment]
The [PDF](https://github.com/SMPTE/rp2129/blob/main/32NF-PCD-RP-2129-Inter%20Entity%20Trust%20Boundary-2022-01-14.pdf) contains text that is intended for the editor and should not be present in the published version. See example below.

![Example](https://user-images.githubusercontent.com/4871350/152659948-40f400f4-0c7a-4fa9-994d-90f3416bf7a0.png)

**Comment by danielsmpte** [comment]
Thank you @palemieux. I'll get that deleted.
